# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-24 04:51
from __future__ import unicode_literals

from django.db import migrations


def make_languages(apps, schema_editor):
    # File formats
    from codeschool.core.models.fileformat import format_processor

    def process(L):
        FileFormat = apps.get_model('core', 'fileformat')

        for kwargs in L:
            FileFormat.objects.create(**kwargs)

    format_processor(process)


def make_syspages(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'contenttype')

    # Hidden root
    apps.get_model('core', 'hiddenroot').objects.create(
        path="00010002",
        depth=2,
        numchild=1,
        title="Hidden pages",
        slug="hidden",
        url_path="/hidden/",
        live=False,
        locked=True,
        content_type=ContentType.objects.get_or_create(
            model='hiddenroot',
            app_label='core',
        )[0],
    )

    # Rogue root
    apps.get_model('core', 'rogueroot').objects.create(
        path="000100020001",
        depth=3,
        numchild=0,
        title="Pages with no parent",
        slug="rogue",
        url_path="/rogue/",
        live=False,
        locked=True,
        content_type=ContentType.objects.get_or_create(
            model='rogueroot',
            app_label='core',
        )[0],
    )

    # Fix the number of children in the root node
    page_cls = apps.get_model('wagtailcore', 'page')
    root = page_cls._default_manager.get(path='0001')  # .objects is not working (?!)
    root.numchild += 1
    root.save(update_fields=['numchild'])


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0001_initial'),
        ('wagtailcore', '0002_initial_data'),
    ]

    operations = [
        migrations.RunPython(make_languages),
        migrations.RunPython(make_syspages),
    ]
