# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 17:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSubmission',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('activities.submission',),
        ),
    ]
