# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_auto_20160811_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formquestion',
            name='is_imported_question',
        ),
        migrations.RemoveField(
            model_name='formquestion',
            name='points_value',
        ),
        migrations.AlterField(
            model_name='formquestion',
            name='score_value',
            field=models.IntegerField(blank=True, help_text="Points may be awarded in specific contexts (e.g., associated with a quiz or in a list of activities) and in Codeschool's generic ranking system.", verbose_name='value'),
        ),
    ]
