# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-13 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0005_auto_20160811_1916'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formquestion',
            old_name='score_value',
            new_name='points_value',
        ),
    ]
