# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0007_auto_20160813_1814'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formquestion',
            name='stars_total',
            field=models.DecimalField(blank=True, decimal_places=1, default=0.0, help_text='Number of stars the activity is worth (fractional stars are accepted). Stars are optional bonus points for special accomplishments that can be used to trade "special powers" in codeschool.', max_digits=5, verbose_name='stars'),
        ),
    ]
