# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-06 17:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('coding_io', '0001_initial'),
        ('questions', '0001_initial'),
        ('core', '0002_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodingIoSubmission',
            fields=[
            ],
            options={
                'proxy': True,
            },
            bases=('questions.questionsubmission',),
        ),
        migrations.AddField(
            model_name='codingioquestion',
            name='language',
            field=models.ForeignKey(blank=True, help_text='Programming language associated with question. Leave it blank in order to accept submissions in any programming language. This option should be set only for questions that tests specific programming languages constructs or require techniques that only make sense in specific programming languages.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.ProgrammingLanguage'),
        ),
        migrations.AddField(
            model_name='answerkey',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='core.ProgrammingLanguage'),
        ),
        migrations.AddField(
            model_name='answerkey',
            name='question',
            field=modelcluster.fields.ParentalKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='coding_io.CodingIoQuestion'),
        ),
        migrations.AlterUniqueTogether(
            name='answerkey',
            unique_together=set([('question', 'language')]),
        ),
    ]
