# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-07 04:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20160806_1522'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='session',
            new_name='response',
        ),
    ]
