# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-11 21:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20160811_1823'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activitysection',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='activitysection',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='activitysection',
            name='points_value',
        ),
        migrations.RemoveField(
            model_name='activitysection',
            name='score_value',
        ),
        migrations.RemoveField(
            model_name='activitysection',
            name='stars_value',
        ),
    ]
