# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-12 23:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0006_auto_20160811_1823'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='final_grade',
            field=models.DecimalField(blank=True, decimal_places=3, help_text="Similar to given_grade, but can account for additional factors such as delay penalties or for any other reason the teacher may want to override the student's grade.", max_digits=6, null=True, verbose_name='final grade'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='given_grade',
            field=models.DecimalField(blank=True, decimal_places=3, help_text='This grade is given by the auto-grader and represents the grade for the response before accounting for any bonuses or penalties.', max_digits=6, null=True, verbose_name='percentage of maximum grade'),
        ),
    ]
