# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-15 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0008_auto_20160814_2208'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='stars',
            field=models.FloatField(default=0),
        ),
    ]
