# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 17:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0009_auto_20160815_1342'),
    ]

    operations = [
        migrations.RenameField(
            model_name='response',
            old_name='given_points',
            new_name='points',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='given_score',
            new_name='score',
        ),
        migrations.RenameField(
            model_name='response',
            old_name='given_stars',
            new_name='stars',
        ),
    ]
