# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-12 23:41
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('wagtailcore', '0028_merge'),
        ('gamification', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TotalScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('points', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('stars', models.FloatField(default=0.0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserScores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('points', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('stars', models.FloatField(default=0.0)),
                ('used_stars', models.FloatField(default=0.0)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailcore.Page')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='accumulatedpoints',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accumulatedpoints',
            name='page',
        ),
        migrations.RemoveField(
            model_name='accumulatedpoints',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='accumulatedscore',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accumulatedscore',
            name='page',
        ),
        migrations.RemoveField(
            model_name='accumulatedscore',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='accumulatedstars',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='accumulatedstars',
            name='page',
        ),
        migrations.RemoveField(
            model_name='accumulatedstars',
            name='user',
        ),
        migrations.RemoveField(
            model_name='pointstotal',
            name='page',
        ),
        migrations.RemoveField(
            model_name='scoretotal',
            name='page',
        ),
        migrations.RemoveField(
            model_name='starstotal',
            name='page',
        ),
        migrations.DeleteModel(
            name='AccumulatedPoints',
        ),
        migrations.DeleteModel(
            name='AccumulatedScore',
        ),
        migrations.DeleteModel(
            name='AccumulatedStars',
        ),
        migrations.DeleteModel(
            name='PointsTotal',
        ),
        migrations.DeleteModel(
            name='ScoreTotal',
        ),
        migrations.DeleteModel(
            name='StarsTotal',
        ),
    ]
