# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-13 21:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0028_merge'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gamification', '0003_auto_20160812_2100'),
    ]

    operations = [
        migrations.CreateModel(
            name='GivenXp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points', models.IntegerField(default=0)),
                ('token', models.CharField(max_length=100)),
                ('index', models.IntegerField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='totalscore',
            name='score',
        ),
        migrations.RemoveField(
            model_name='userscores',
            name='score',
        ),
        migrations.AddField(
            model_name='badge',
            name='required_score',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='badgetrack',
            name='entry_point',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='badge_tracks', to='wagtailcore.Page'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='badge',
            name='track',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='gamification.BadgeTrack'),
        ),
        migrations.AlterUniqueTogether(
            name='givenxp',
            unique_together=set([('user', 'token', 'index')]),
        ),
    ]
