# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-08-16 17:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamification', '0006_auto_20160816_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='totalscore',
            name='stars',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='stars',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='userscore',
            name='used_stars',
            field=models.DecimalField(decimal_places=1, default=0.0, max_digits=5),
        ),
    ]
